type CharacterProps = {
    id: number,
    name: string,
    smallImg: string,
    bigImg: string,
    alt: string,
    type: "support" | "tank" | "dps" | "none",
    description: string,
  }
  
  export const characters: CharacterProps[] = [
    {
      id: 1,
      name: "Ozul",
      smallImg: "/ozul.png",
      bigImg: "/ozul_big.png",
      alt: "Ozul",
      type: "dps",
      description: "Ozul é um assassino sombrio, mestre em ataques furtivos e letais. Sua presença nas sombras é sinônimo de perigo iminente.",
    },
    {
      id: 2,
      name: "Arryn",
      smallImg: "/arryn.png",
      bigImg: "/arryn_big.png",
      alt: "Arryn",
      type: "dps",
      description: "Arryn é um ágil guerreiro, conhecido por sua velocidade e precisão em combate. Sua lâmina é tão rápida quanto mortal.",
    },
    {
      id: 3,
      name: "Byron",
      smallImg: "/byron.png",
      bigImg: "/byron_big.png",
      alt: "Byron",
      type: "support",
      description: "Byron é um elementalista que manipula os elementos para proteger aliados e desferir ataques devastadores contra inimigos.",
    },
    {
      id: 4,
      name: "Iris",
      smallImg: "/iris.png",
      bigImg: "/iris_big.png",
      alt: "Iris",
      type: "tank",
      description: "Iris é uma ilusionista que utiliza magia para confundir inimigos e proteger seus aliados com escudos mágicos.",
    },
    {
      id: 5,
      name: "Kavras",
      smallImg: "/kavras.png",
      bigImg: "/kavras_big.png",
      alt: "Kavras",
      type: "support",
      description: "Kavras é um necromante poderoso, capaz de invocar os mortos e manipular a energia vital para auxiliar seus aliados.",
    },
    {
      id: 6,
      name: "Korz",
      smallImg: "/korz.png",
      bigImg: "/korz_big.png",
      alt: "Korz",
      type: "tank",
      description: "Korz é um guerreiro imponente, cuja força bruta e resistência o tornam uma muralha intransponível no campo de batalha.",
    },
    {
      id: 7,
      name: "Ojore",
      smallImg: "/ojore.png",
      bigImg: "/ojore_big.png",
      alt: "Ojore",
      type: "tank",
      description: "Ojore é um defensor incansável, sempre na linha de frente para proteger seus companheiros com coragem e determinação.",
    },
    {
      id: 8,
      name: "Ophis",
      smallImg: "/ophis.png",
      bigImg: "/ophis_big.png",
      alt: "Ophis",
      type: "dps",
      description: "Ophis é uma feiticeira misteriosa que canaliza o poder do caos para desferir ataques mágicos de grande intensidade.",
    },
    {
      id: 9,
      name: "Orbryn",
      smallImg: "/orbryn.png",
      bigImg: "/orbryn_big.png",
      alt: "Orbryn",
      type: "dps",
      description: "Orbryn é um arqueiro preciso, cuja habilidade com o arco é incomparável, atingindo alvos com letalidade à distância.",
    },
    {
      id: 10,
      name: "Reya",
      smallImg: "/reya.png",
      bigImg: "/reya_big.png",
      alt: "Reya",
      type: "dps",
      description: "Reya é uma guerreira elétrica, que combina velocidade e ataques de raio para eliminar seus inimigos rapidamente.",
    },
    {
      id: 11,
      name: "Thomas",
      smallImg: "/thomas.png",
      bigImg: "/thomas_big.png",
      alt: "Thomas",
      type: "support",
      description: "Thomas é um bardo felino que utiliza melodias encantadoras para fortalecer aliados e enfraquecer adversários.",
    },
    {
      id: 12,
      name: "Urijor",
      smallImg: "/urijor.png",
      bigImg: "/urijor_big.png",
      alt: "Urijor",
      type: "tank",
      description: "Urijor, conhecido como o 'Druida Louco', manipula a natureza de forma imprevisível para proteger e atacar com ferocidade.",
    },
    {
      id: 13,
      name: "Faendar",
      smallImg: "/faendar.png",
      bigImg: "/faendar_big.png",
      alt: "faendar",
      type: "tank",
      description: "PLACEHOLDER",
    },
    {
      id: 14,
      name: "irhaal",
      smallImg: "/irhaal.png",
      bigImg: "/irhaal_big.png",
      alt: "irhaal",
      type: "tank",
      description: "PLACEHOLDER",
    },
    {
      id: 15,
      name: "liam",
      smallImg: "/liam.png",
      bigImg: "/liam_big.png",
      alt: "liam",
      type: "tank",
      description: "PLACEHOLDER",
    },
    {
      id: 16,
      name: "marly",
      smallImg: "/marly.png",
      bigImg: "/marly_big.png",
      alt: "marly",
      type: "support",
      description: "PLACEHOLDER",
    },
    {
      id: 17,
      name: "mohazus",
      smallImg: "/mohazus.png",
      bigImg: "/mohazus_big.png",
      alt: "mohazus",
      type: "tank",
      description: "PLACEHOLDER",
    },
    {
      id: 18,
      name: "yuki",
      smallImg: "/yuki.png",
      bigImg: "/yuki_big.png",
      alt: "yuki",
      type: "tank",
      description: "PLACEHOLDER",
    },
    {
      id: 19,
      name: "yura",
      smallImg: "/yura.png",
      bigImg: "/yura_big.png",
      alt: "yura",
      type: "dps",
      description: "PLACEHOLDER",
    },
    {
      id: 20,
      name: "zeugladius",
      smallImg: "/zeugladius.png",
      bigImg: "/zeugladius_big.png",
      alt: "zeugladius",
      type: "tank",
      description: "PLACEHOLDER",
    },
  ];
  